### ISSUE TITLE
Vite Error on build

### ISSUE THREAD

**Issue by oleghalin** [nathanchase/dayjs#1]
` ERROR  [vite:load-fallback] Could not load dayjs/plugin/Utc.js (imported by virtual:nuxt:/opt/service/.nuxt/dayjs.config.mjs): ENOENT: no such file or directory, open 'dayjs/plugin/Utc.js'`

Building in Docker, node-18-alpine

**Comment by wasitum** [comment]
I have the same issue, have you found how to correct this ?

**Comment by oleghalin** [comment]
Hello. problem was very fun :) Plugin called `utc`, not `Utc`
