### ISSUE TITLE
error when using others options

### ISSUE THREAD

**Issue by joseehilton147** [nathanchase/dayjs#13]
Really ty for this port, but when i try to use others config plugins options a error occur:

with this works:
dayjs: {
plugins: ['duration', 'relativeTime', 'advancedFormat', 'weekday'],
},

with this dont:
dayjs: {
locales: ['en', 'ja'],
defaultLocale: 'en',
defaultTimeZone: 'Asia/Tokyo',
plugins: ['duration', 'relativeTime', 'advancedFormat', 'weekday'],
},

how can i set a defaultLocale and timezone on your plugin

**Comment by nathanchase** [comment]
Just pushed v1.0.12 which may solve your issue. Please upgrade and see if it works for you!
https://www.npmjs.com/package/@nathanchase/nuxt-dayjs-module
