### ISSUE TITLE
Strongly typed $dayjs from useNuxtApp()

### ISSUE THREAD

**Issue by bradlis7** [nathanchase/dayjs#18]
$dayjs is of `unknown` type in my `<script lang="ts">`, so it works fine, but VSCode gives me errors when I try to use it.

![image](https://user-images.githubusercontent.com/7062604/225738609-991a9b20-881f-489e-8256-74868f33269c.png)

**Comment by nathanchase** [comment]
Hmm... when you import dayjs itself, and use it in a plugin, it simply uses `dayjs: typeof dayjs`. I'm not sure why the module would be any different. Will have to look into it.

**Comment by Harm-Nullix** [comment]
This module should implement something like 
```
declare module '#app' {
  interface NuxtApp {
    $dayjs: typeof dayjs
  }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $dayjs: typeof dayjs
  }
}
```

**Comment by nathanchase** [comment]
Ok, I've added the type def to the `provide` and pushed a new version. Try and see if this solves your issue!
https://github.com/nathanchase/dayjs/commit/168a853b2a47150f7ba2089fc0a662e5781cfd1f

**Comment by bradlis7** [comment]
Looks like the fix actually caused #22 .

I do have a `NuxtApp.d.ts` file that looks like what @Harm-Nullix suggested, and it has been working in my project, but it would be nice to fix it in the project itself.

```
import * as dayjs from 'dayjs';
import dayOfYear from 'dayjs/plugin/dayOfYear';

// nathanchase/dayjs doesn't seem to resolve for us, so I'm setting the type here.
declare module "#app" { // or "@nuxt/schema"
    interface NuxtApp {
        $dayjs: typeof dayjs & typeof dayOfYear
    }
}
```

**Comment by nathanchase** [comment]
Yeah, still trying to debug this and figure it out.

**Comment by nathanchase** [comment]
Now I'm getting a rollup error trying to build at all... If anyone else wants to take a stab at this and submit a PR, be my guest. I'm not getting anywhere with this locally.

**Comment by Harm-Nullix** [comment]
Hey, sorry for not responding today, busy day @ the office ^^

I made a PR, but I cannot see in the package how you do your rollup so that is up to you.
The `npm run prepack` command ran successfully, so that is something :)

**Comment by bradlis7** [comment]
@Harm-Nullix is it possible to automatically include plugins if they are loaded in nuxt config? If I have dayOfYear loaded, `dayjs().dayOfYear()` is showing up as an error.
