### ISSUE TITLE
after upgrade to 1.0.14 gives a error

### ISSUE THREAD

**Issue by joseehilton147** [nathanchase/dayjs#22]
![image](https://user-images.githubusercontent.com/53986027/230186713-779fd67f-71b7-4f53-bb2b-dd4d06c3098b.png)

downgrading to 1.0.13 works normally

im using nuxt 3.3.3

**Comment by bradlis7** [comment]
`typeof dayjs` is just setting it to string `"function"`

**Comment by Harm-Nullix** [comment]
Yes, you shouldn't use 1.0.14
It is confirmed broken by the owner https://github.com/nathanchase/dayjs/issues/18#issuecomment-1498199194
You should downgrade or wait for the next release, there is nothing new in 1.0.14 over 1.0.13.

**Comment by nathanchase** [comment]
Please try https://github.com/nathanchase/dayjs/releases/tag/1.0.15 and let me know if it works for you! It did for me locally.

**Comment by joseehilton147** [comment]
fixed, ty
