### ISSUE TITLE
Support default language settings?

### ISSUE THREAD

**Issue by initred** [nathanchase/dayjs#7]
Support default language settings?
I set locale as follows, but it didn't work.

```ts
export default defineNuxtConfig({
 modules: [
    '@nathanchase/nuxt-dayjs-module'
  ],
  dayjs: {
    locales: [
      'ko'
    ],
    defaultLocale: 'ko',
    plugins: [
      'relativeTime',
      'isoWeek',
      'utc',
      'weekday',
      'isToday',
      'isSameOrBefore',
      'isSameOrAfter',
      'localizedFormat',
      'timezone',
      'updateLocale'
    ]
  }
})
```

Thank you for your open source contribution!

**Comment by nathanchase** [comment]
Yeah, currently it only supports plugins in the config. I can take a look and see if it's easy to add the locales like you have above. Thanks for the request.

**Comment by nathanchase** [comment]
[The code actually looks like locales are already supported](https://github.com/nathanchase/dayjs/blob/master/src/gen.ts), but maybe you have to add `localeData` as a plugin? https://day.js.org/docs/en/plugin/locale-data

Sorry, I've not dealt with locales and dayjs before.

**Comment by initred** [comment]
@nathanchase Thank you for your reply.

**Comment by nathanchase** [comment]
Were you able to get it working @initred? Did the localeData plug-in do the trick?

**Comment by initred** [comment]
@nathanchase @rafaponieman I created a new module and developed it. All types are supported and all functions are functional. However, the testing code and error handling are insufficient. If you're in a hurry, you can use it.
There was no particular error when I used it.

**Comment by josedotjs** [comment]
Hi @nathanchase @rafaponieman @initred, i have issues with multi lang support.
My solution was change the line 
`${locales.map(l => `import 'dayjs/locale/${l}'`).join('\n')}`
to
`${locales.map(l => `import 'dayjs/esm/locale/${l}'`).join('\n')}`
in  src/gen.ts because you are loading dayjs from dayjs/esm/index.js, and now works great.
Thanks for this module @nathanchase

**Comment by nathanchase** [comment]
> Hi @nathanchase @rafaponieman @initred, i have issues with multi lang support.
> 
> My solution was change the line 
> 
> `${locales.map(l => `import 'dayjs/locale/${l}'`).join('\n')}`
> 
> to
> 
> `${locales.map(l => `import 'dayjs/esm/locale/${l}'`).join('\n')}`
> 
> in  src/gen.ts because you are loading dayjs from dayjs/esm/index.js, and now works great.
> 
> Thanks for this module @nathanchase 

Thanks! Submit this as PR and I can merge in this fix.
