### ISSUE TITLE
RelativeTime

### ISSUE THREAD

**Issue by luminous8** [nathanchase/dayjs#8]
Great module, thanks for the work!

i'm looking to customize the relative time like here
https://day.js.org/docs/en/customization/relative-time

Here's my code
`dayjs: {
    plugins: ['relativeTime', 'UpdateLocale'],
    relativeTime: {
      future: 'in %s',
      past: '%s ago',
      s: 'today',
      m: 'today',
      mm: 'today',
      h: 'an hour',
      hh: '%d hours',
      d: 'a day',
      dd: '%d days',
      M: 'a month',
      MM: '%d months',
      y: 'a year',
      yy: '%d years',
    },
  },`
  
But it doesn't work (no error message but no change on the output)

Any idea on how to customize this?

**Comment by nathanchase** [comment]
I believe you'd have to set the relativeTime options inside your code, not as a configuration of the dayjs module. I'm using relativeTime with this module now and `$dayjs(string).fromNow()` works as expected - and that relies on relativeTime.

So wherever in your code you need to use the customized strings, you'd do:
```
dayjs.updateLocale('en', {
  relativeTime: {
    future: "in %s",
    past: "%s ago",
    s: 'a few seconds',
    m: "a minute",
    mm: "%d minutes",
    h: "an hour",
    hh: "%d hours",
    d: "a day",
    dd: "%d days",
    M: "a month",
    MM: "%d months",
    y: "a year",
    yy: "%d years"
  }
})
```

**Comment by luminous8** [comment]
Thanks!
I just have to put this
`dayjs.updateLocale('en', {
  relativeTime: {
    future: "in %s",
    past: "%s ago",
    s: 'a few seconds',
    m: "a minute",
    mm: "%d minutes",
    h: "an hour",
    hh: "%d hours",
    d: "a day",
    dd: "%d days",
    M: "a month",
    MM: "%d months",
    y: "a year",
    yy: "%d years"
  }
})`

inside my `<script setup>`?
Because i have a `dayjs is not defined` error

i'm new to nuxt 3 and I'm not sure how to call the module inside the script tag

**Comment by nathanchase** [comment]
No problem! You'll just need to access the "context" in Nuxt 3 by using `useNuxtApp()`. This would be in your pages, or components, or composables.

So it would be just:

`const { $dayjs } = useNuxtApp();`

Then you can access $dayjs() as a function in your script or template.

**Comment by luminous8** [comment]
Thanks so much, it worked!
